server:
  servlet:
    context-path: /commission
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction
    username: root
    password: abcd1234
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: abcd1234
    virtual-host: /
payment:
  service:
    url: http://localhost:8081
